version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/nestjsdb
      - BULL_REDIS_HOST=redis
      - BULL_REDIS_PORT=6379
      - API_KEY=my-secret-api-key
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data: